### ISSUE TITLE
Redirect 404 to root

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#13] opened 2015-11-23 19:19 UTC

**Comment by schlosser** [comment] 2016-02-03 23:41
This is actually a cerberus decision, because of how static hosting works.  Then, once we deploy on minimill.co, it will be an nginx decision.  That said I'm going to keep this bug here as a reminder.

**Comment by jhil** [comment] 2016-02-04 19:45
:+1:

**Comment by schlosser** [comment] 2016-02-09 00:44
close at duplicate of #30

**Closed as completed by schlosser** 2016-02-09 00:44 UTC
